import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {execFileSync} from 'node:child_process';
function assert(c:unknown,m:string):asserts c{if(!c)throw new Error(m)}
// Exact anchor excerpts read from GitHub commit 6608e1e2fa620fd71f3356e063bac862ede6fdc5.
const server=`import express from "express";\nimport path from "path";\nimport { createServer as createViteServer } from "vite";\nimport dotenv from "dotenv";\nimport { GoogleGenAI } from "@google/genai";\nimport { extractSongDNA } from "./server/music/song-dna";\nimport { buildProductionBlueprint } from "./server/music/production-blueprint";\nimport { buildGeminiMusicBrief, buildLyriaPrompt } from "./server/music/gemini-music-brief";\nimport { prepareComposition, generateLeadSheet, generateArrangement } from "./server/music/composer";\nasync function startServer() {\n  const app = express();\n  app.post("/api/compose/prepare", async (req, res) => {\n    try {\n      const { idea, styleId } = req.body;\n    } catch {}\n  });\n}`;
const runs=`import React, { useEffect, useMemo, useState } from 'react';\nimport { Archive, CloudDownload, FileMusic, Loader2, RefreshCw } from 'lucide-react';\nimport { ProjectList } from '../components/projects/ProjectList';\nimport { ProjectToolbar } from '../components/projects/ProjectToolbar';\nimport { ResultWorkspace } from '../components/ResultWorkspace';\nasync function arrangeSelectedProject(){\n      const arrangeResponse = await fetch('/api/compose/arrange', {\n        method: 'POST',\n        headers: { 'Content-Type': 'application/json' },\n        body: JSON.stringify({\n          leadSheetXml: leadRevision.musicXml,\n          arrangePrompt: context.arrangePrompt,\n          arrangeDocRefs: context.arrangeDocRefs,\n          songRequest: context.songRequest,\n          styleId: workingBundle.project.style,\n        }),\n      });\n      const arrangeData = await arrangeResponse.json();\n      if (!arrangeResponse.ok) {\n        const failure: any = new Error(arrangeData?.error?.message || arrangeData?.error || 'Phối khí thất bại.');\n        failure.code = arrangeData?.error?.code;\n        throw failure;\n      }\n      if (typeof arrangeData?.xml !== 'string' || !arrangeData.xml.trim()) throw new Error('Máy chủ không trả về MusicXML bản phối.');\n\n      const next = await projectService.appendRevision(workingBundle, {\n        musicXml: arrangeData.xml,\n        reason: 'arrange',\n        label: 'Bản phối',\n      });\n      await saveBundle(next);\n}`;
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'musicpro-sha6608-anchor-'));fs.writeFileSync(path.join(dir,'server.ts'),server);fs.mkdirSync(path.join(dir,'src/views'),{recursive:true});fs.writeFileSync(path.join(dir,'src/views/RunsView.tsx'),runs);fs.mkdirSync(path.join(dir,'scripts'));fs.copyFileSync('scripts/apply-auto-production-v1.4.1.mjs',path.join(dir,'scripts/apply-auto-production-v1.4.1.mjs'));
execFileSync(process.execPath,['scripts/apply-auto-production-v1.4.1.mjs'],{cwd:dir,stdio:'pipe'});
const patchedServer=fs.readFileSync(path.join(dir,'server.ts'),'utf8'),patchedRuns=fs.readFileSync(path.join(dir,'src/views/RunsView.tsx'),'utf8');
assert(patchedServer.includes('AUTO_PRODUCTION_V1_4_1')&&patchedServer.includes('/api/compose/run-stream'),'exact SHA server anchors must patch cleanly');
assert(patchedRuns.includes('PROJECT_ARRANGEMENT_PRODUCTION_V1_4_1')&&patchedRuns.includes('bindProductionSnapshotToRevision'),'exact SHA RunsView anchors must patch cleanly');
console.log('PASS installer-sha6608-anchor');
