import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, Circle, Clock3, Loader2, ShieldCheck, Sparkles } from 'lucide-react';
import type { AutoComposeEvent, AutoComposeStepSummary, ComposeStep, ProductionReadinessReport } from '../../compose/types';

interface Props {
  events: AutoComposeEvent[];
  running: boolean;
  startedAt?: number;
  readiness?: ProductionReadinessReport;
  estimatedTotalSeconds?: number;
}

const STEP_LABELS:Record<ComposeStep,string>={1:'Bước 1 · Hiểu ý tưởng',2:'Bước 2 · Phương án sáng tác',3:'Bước 3 · Bản nhạc',4:'Bước 4 · Phối khí'};
function formatDuration(seconds:number):string { const safe=Math.max(0,Math.round(seconds)),m=Math.floor(safe/60),s=safe%60; return m>0?`${m}:${String(s).padStart(2,'0')}`:`0:${String(s).padStart(2,'0')}`; }
function StepSummary({summary}:{summary:AutoComposeStepSummary}) { return <div className="rounded-xl border border-white/10 bg-black/30 p-4"><div className="mb-3 flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-400"/><h4 className="font-bold text-white">{summary.title}</h4></div><div className="grid gap-2 sm:grid-cols-2">{summary.items.map((item,index)=><div key={`${item.label}-${index}`} className="rounded-lg bg-white/[0.035] px-3 py-2"><div className="text-[10px] font-bold uppercase tracking-wider text-zinc-600">{item.label}</div><div className="mt-1 whitespace-pre-wrap text-sm text-zinc-200">{item.value}</div></div>)}</div>{summary.quality&&<div className={`mt-3 rounded-lg border px-3 py-2 text-xs font-bold ${summary.quality.status==='PASS'?'border-emerald-500/25 bg-emerald-500/10 text-emerald-300':'border-red-500/25 bg-red-500/10 text-red-300'}`}>QUALITY GATE {summary.quality.status} · {summary.quality.score}/100</div>}</div>; }

export const AutoComposeProgress:React.FC<Props>=({events,running,startedAt,readiness,estimatedTotalSeconds=240})=>{
  const [now,setNow]=useState(()=>Date.now());
  useEffect(()=>{if(!running)return;const id=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(id);},[running]);
  const current=events[events.length-1],progress=Math.max(0,Math.min(100,current?.progress||0)),elapsed=startedAt?Math.max(0,(now-startedAt)/1000):0;
  const providerWait=running&&current?.indeterminate===true,lastUpdateAge=current?.at?Math.max(0,(now-current.at)/1000):0;
  const eta=useMemo(()=>{if(!running||progress>=100)return 0;const historyRemaining=Math.max(0,estimatedTotalSeconds*(100-progress)/100);if(progress<8||elapsed<8)return historyRemaining;const projected=elapsed*(100-progress)/Math.max(1,progress);return Math.max(5,Math.round(projected*.55+historyRemaining*.45));},[elapsed,estimatedTotalSeconds,progress,running]);
  const overdue=running&&progress<100&&elapsed>estimatedTotalSeconds;
  const summaries=new Map<ComposeStep,AutoComposeStepSummary>(); for(const event of events)if(event.summary)summaries.set(event.step,event.summary);
  const currentStep=current?.step||1,haltedStep=[...events].reverse().find(event=>event.kind==='halted')?.step,cancelledStep=[...events].reverse().find(event=>event.kind==='cancelled')?.step;
  const completedSteps=new Set(events.filter(event=>event.kind==='step-summary'||event.kind==='complete'||(event.kind==='artifact'&&event.quality?.status!=='FAIL')).map(event=>event.step));
  const activity=events.filter(event=>event.kind==='progress'||event.kind==='retry'||event.kind==='quality'||event.kind==='halted'||event.kind==='cancelled').slice(-6).reverse();
  if(!events.length)return null;
  return <div className="space-y-4 rounded-2xl border border-indigo-500/20 bg-indigo-500/[0.045] p-4 md:p-5" aria-live="polite">
    <div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><div className="flex items-center gap-2 text-sm font-black uppercase tracking-[0.14em] text-indigo-300">{running?<Loader2 className="h-4 w-4 animate-spin"/>:haltedStep||cancelledStep?<AlertTriangle className="h-4 w-4 text-amber-400"/>:<Sparkles className="h-4 w-4"/>}{running?'Đang tạo bài hát':cancelledStep?'Đã dừng quy trình':haltedStep?'Quy trình cần rà soát':'Quy trình sáng tác'}</div><div className="mt-1 text-lg font-bold text-white">{current?.label||'Chuẩn bị'}</div>{current?.detail&&<p className="mt-1 max-w-3xl text-sm text-zinc-400">{current.detail}</p>}</div><div className="flex shrink-0 flex-wrap gap-2 text-xs text-zinc-400"><span className="inline-flex items-center gap-1 rounded-lg border border-white/10 bg-black/30 px-2.5 py-1.5"><Clock3 className="h-3.5 w-3.5"/>Đã chạy {formatDuration(elapsed)}</span>{running&&!overdue&&<span className="rounded-lg border border-white/10 bg-black/30 px-2.5 py-1.5">Ước tính còn ~{formatDuration(eta)}</span>}{overdue&&<span className="rounded-lg border border-amber-500/20 bg-amber-500/10 px-2.5 py-1.5 text-amber-300">Đang hoàn thiện · lâu hơn dự kiến ~{formatDuration(elapsed-estimatedTotalSeconds)}</span>}</div></div>
    <div><div className="mb-1 flex justify-between text-[11px] text-zinc-500"><span>{providerWait?'Đang xử lý trên server':'Tiến độ'}</span><span>{providerWait?`Mốc công đoạn ${Math.round(progress)}%`:`${Math.round(progress)}%`}</span></div><div className="h-2 overflow-hidden rounded-full bg-black/60">{providerWait?<div className="h-full w-full animate-pulse rounded-full bg-indigo-500/70"/>:<div className="h-full rounded-full bg-indigo-500 transition-[width] duration-500" style={{width:`${progress}%`}}/>}</div>{providerWait&&<div className="mt-1 flex justify-between text-[10px] text-zinc-600"><span>Gemini/server vẫn đang xử lý · không có % token đáng tin cậy</span><span>cập nhật cuối {formatDuration(lastUpdateAge)} trước</span></div>}</div>
    <div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{([1,2,3,4] as ComposeStep[]).map(step=>{const done=completedSteps.has(step)||progress===100,halted=haltedStep===step,cancelled=cancelledStep===step,active=running&&currentStep===step&&!done;return <div key={step} className={`flex items-center gap-2 rounded-xl border px-3 py-2 text-sm ${done?'border-emerald-500/20 bg-emerald-500/5 text-emerald-300':halted||cancelled?'border-amber-500/30 bg-amber-500/10 text-amber-300':active?'border-indigo-500/30 bg-indigo-500/10 text-indigo-200':'border-white/10 bg-black/20 text-zinc-600'}`}>{done?<CheckCircle2 className="h-4 w-4"/>:halted||cancelled?<AlertTriangle className="h-4 w-4"/>:active?<Loader2 className="h-4 w-4 animate-spin"/>:<Circle className="h-4 w-4"/>}{STEP_LABELS[step]}</div>;})}</div>
    {!!activity.length&&<div className="rounded-xl border border-white/10 bg-black/25 p-3"><div className="mb-2 text-[10px] font-bold uppercase tracking-wider text-zinc-600">Tiến độ công đoạn</div><div className="space-y-1.5">{activity.map((event,index)=><div key={`${event.at}-${index}`} className="flex gap-2 text-xs"><span className={`mt-1 h-1.5 w-1.5 shrink-0 rounded-full ${event.kind==='halted'||event.kind==='cancelled'?'bg-amber-400':'bg-indigo-400'}`}/><span className="text-zinc-400"><b className="text-zinc-300">{event.label}</b>{event.detail?` — ${event.detail}`:''}</span></div>)}</div></div>}
    {[1,2,3,4].map(step=>summaries.get(step as ComposeStep)).filter(Boolean).map((summary,index)=><div key={`${summary!.title}-${index}`}><StepSummary summary={summary!}/></div>) }
    {readiness&&<div className={`rounded-xl border p-4 ${readiness.status==='PASS'?'border-emerald-500/30 bg-emerald-500/10':'border-amber-500/30 bg-amber-500/10'}`}><div className="flex items-start gap-3"><ShieldCheck className={`mt-0.5 h-5 w-5 ${readiness.status==='PASS'?'text-emerald-400':'text-amber-400'}`}/><div><div className="font-black text-white">Production Readiness: {readiness.status}</div><div className="mt-1 text-sm text-zinc-300">{readiness.label} · {readiness.score}/100</div><div className="mt-1 text-xs text-zinc-500">{readiness.summary}</div></div></div>{readiness.blockers?.length>0&&<div className="mt-3 rounded-lg bg-black/25 p-3"><div className="mb-1 text-[10px] font-black uppercase tracking-wider text-amber-300">Blocker cần xử lý</div>{readiness.blockers.slice(0,5).map((item,index)=><div key={index} className="mt-1 text-xs text-zinc-300">• {item}</div>)}</div>}</div>}
  </div>;
};
